### ISSUE TITLE
Deployed Versions Tile - "KeyError: 'environment_id' in"

### ISSUE THREAD

**Issue by brhahlen** [xebialabs-community/xlr-xldeploy-plugin#42]
When selecting an existing environment in the Deployed Versions Tile, an error is thrown which reads:
```
2017-01-25 09:27:23.384 [qtp169833205-22214] {request=/tiles/Applications/Folder784315945/Release54048206/summary/Tile509385314/data, method=GET, username=admin} ERROR c.x.d.UnhandledExceptionMapper - Unhandled Exception: {}
java.lang.RuntimeException: javax.script.ScriptException: KeyError: 'environment_id' in <script> at line number 17

Caused by: javax.script.ScriptException: KeyError: 'environment_id' in <script> at line number 17
        at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
        at com.xebialabs.xlrelease.script.ScriptExecutor.lambda$evalScriptPrivileged$92(ScriptExecutor.java:92)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.xebialabs.xlrelease.script.ScriptExecutor.evalScriptPrivileged(ScriptExecutor.java:91)
        at com.xebialabs.xlrelease.script.ScriptExecutor.evalScriptWithUtilities(ScriptExecutor.java:85)
        at com.xebialabs.xlrelease.script.ScriptExecutor.evalScript(ScriptExecutor.java:66)
        at com.xebialabs.xlrelease.script.ScriptService.executeScript(ScriptService.java:646)
        at com.xebialabs.xlrelease.script.ScriptService.executeScriptWithWriter(ScriptService.java:227)
        ... 93 common frames omitted
Caused by: org.python.core.PyException: null
        at org.python.core.Py.KeyError(Py.java:249)
        at org.python.core.PyObject.__getitem__(PyObject.java:738)
        at xldeploy.XLDeployClient$py.get_deployed_applications_for_environment$44(__pyclasspath__/xldeploy/XLDeployClient.py:382)
        at xldeploy.XLDeployClient$py.call_function(__pyclasspath__/xldeploy/XLDeployClient.py)
```

**Comment by jdewinne** [comment]
Thanks for reporting. Fixed in [v2.8.3](https://github.com/xebialabs-community/xlr-xldeploy-plugin/releases/tag/v2.8.3)

**Comment by brhahlen** [comment]
Unfortunately, this is not fixed.
Still getting the same error.
Full error:
```
2017-01-27 03:10:16.661 [qtp169833205-68] {request=/tiles/Applications/Folder784315945/Release54048206/summary/Tile193315295/data, method=GET, username=hah260} ERROR c.x.d.UnhandledExceptionMapper - Unhandled Exception: {}
java.lang.RuntimeException: javax.script.ScriptException: KeyError: 'environment_id' in <script> at line number 17
        at com.xebialabs.xlrelease.script.ScriptService.executeScriptWithWriter(ScriptService.java:230)
        at com.xebialabs.xlrelease.plugins.dashboard.service.TileScriptExecutor.executeTileScript(TileScriptExecutor.scala:31)
        at com.xebialabs.xlrelease.plugins.dashboard.service.TileScriptExecutor$$FastClassBySpringCGLIB$$dfb8b7d0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:320)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:353)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at com.xebialabs.xlrelease.plugins.dashboard.service.TileScriptExecutor$$EnhancerBySpringCGLIB$$1c34dbc0.executeTileScript(<generated>)
        at com.xebialabs.xlrelease.plugins.dashboard.service.TileService.executeTileDataScript(TileService.scala:35)
        at com.xebialabs.xlrelease.plugins.dashboard.api.internal.TileResource.getTileData(TileResource.scala:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
        at com.xebialabs.deployit.core.rest.resteasy.WorkdirInjectorFactory$WorkdirMethodInjector.invoke(WorkdirInjectorFactory.java:48)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at com.xebialabs.deployit.plumbing.RequestLocal.doFilter(RequestLocal.java:21)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.xebialabs.deployit.plumbing.VersionEnforcerFilter.doFilter(VersionEnforcerFilter.java:39)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:133)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at com.xebialabs.license.LicenseValidationFilter.doFilter(LicenseValidationFilter.java:61)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.xebialabs.deployit.plumbing.LogbackFilter.doFilter(LogbackFilter.java:25)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.xebialabs.deployit.plumbing.AccessLogFilter.doFilter(AccessLogFilter.java:22)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.script.ScriptException: KeyError: 'environment_id' in <script> at line number 17
        at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
        at com.xebialabs.xlrelease.script.ScriptExecutor.lambda$evalScriptPrivileged$92(ScriptExecutor.java:92)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.xebialabs.xlrelease.script.ScriptExecutor.evalScriptPrivileged(ScriptExecutor.java:91)
        at com.xebialabs.xlrelease.script.ScriptExecutor.evalScriptWithUtilities(ScriptExecutor.java:85)
        at com.xebialabs.xlrelease.script.ScriptExecutor.evalScript(ScriptExecutor.java:66)
        at com.xebialabs.xlrelease.script.ScriptService.executeScript(ScriptService.java:646)
        at com.xebialabs.xlrelease.script.ScriptService.executeScriptWithWriter(ScriptService.java:227)
        ... 93 common frames omitted
Caused by: org.python.core.PyException: null
        at org.python.core.Py.KeyError(Py.java:249)
        at org.python.core.PyObject.__getitem__(PyObject.java:738)
        at xldeploy.XLDeployClient$py.get_deployed_applications_for_environment$45(__pyclasspath__/xldeploy/XLDeployClient.py:398)
        at xldeploy.XLDeployClient$py.call_function(__pyclasspath__/xldeploy/XLDeployClient.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:145)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at org.python.pycode._pyx20.f$0(<script>:19)
        at org.python.pycode._pyx20.call_function(<script>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.core.__builtin__.eval(__builtin__.java:497)
        at org.python.core.__builtin__.eval(__builtin__.java:501)
        at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
        ... 101 common frames omitted
2017-01-27 03:10:16.662 [qtp169833205-68] {request=/tiles/Applications/Folder784315945/Release54048206/summary/Tile193315295/data, method=GET, username=hah260} WARN  com.xebialabs.deployit.Sanitizer - Found errors during sanitation: discarded tag script
```

**Comment by brhahlen** [comment]
We are using XLR 6.0.0 and XLD 6.0.2
If you need more info, let me know :-)

**Comment by jdewinne** [comment]
Thanks. I've added INSPECTION and DEFAULT, which should fix this properly. Can you try [v2.8.5](https://github.com/xebialabs-community/xlr-xldeploy-plugin/releases/tag/v2.8.5)?

**Comment by jdewinne** [comment]
Fixed another edge case in [v2.8.9](https://github.com/xebialabs-community/xlr-xldeploy-plugin/releases/tag/v2.8.9)
